version: '3'

services:

  mariadb_default:
    image: mariadb
    container_name: final_maria
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT:-0}:3306
    volumes:
      - ./extra/docker/mysql/default:/var/lib/mysql:delegated

